name: DailyLogin

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout actions
      uses: actions/checkout@v2

    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2

    - name: Install dependencies
      run: pip install requests

    - name: Run
      run: |
        python DxxLogin.py
      env: 
        cookies: ${{secrets.COOKIE}}
