name: WeeklyLearn

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout actions
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install

    - name: Run
      run: |
        python DxxLearn.py
      env: 
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
